### ISSUE TITLE
Mobile UI - URI flows beyond metadata table

### ISSUE THREAD

**Issue by pyvandenbussche** [pyvandenbussche/lov#20]
**Mobile UI**

Text spans beyond / flows over the Metadata table borders.

CSS Word-wrap: break-word may or may not be helpful for displaying URIs with mobile devices.

**Comment by gatemezing** [comment]
Probably something to be done as Google detects not mobile friendly? https://www.google.com/webmasters/tools/mobile-friendly/?url=http://lov.okfn.org/dataset/lov/. Of course, LOV already has a target audience and does not need a special ranking ;)
