### ISSUE TITLE
Vocabulary metadata on API v2

### ISSUE THREAD

**Issue by smouzakitis** [pyvandenbussche/lov#21]
Hello! 
Congratulations for your excellent work on your new version!
A quick question, how can i get more details about each vocabulary on the new API?
For instance for a specific vocabulary how can i get the "Download URI" or the "web page" properties?

many thanks!
Spiros

**Comment by pyvandenbussche** [comment]
You are right, I forgot to add an /info to vocabulary and agent types... Will fix that soon.

**Comment by pyvandenbussche** [comment]
Hi Spiros,

the APIs are now published. Check the http://lov.okfn.org/dataset/lov/api page. You now have an API to get all the details about one vocbaulary.

If you iterate on the 'versions' array, and get the latest one (issued) with an existing 'fileURL' key, then the value for that key will return the URL to download the vocab.

Tell me if that works for you and then I close this issue.

Pierre-Yves.

**Comment by smouzakitis** [comment]
Yes this is great! Many thanks!!!!!
