### ISSUE TITLE
Broken links and usability improvements

### ISSUE THREAD

**Issue by alberto-ieru** [pyvandenbussche/lov#26]
There is a bunch of vocabularies whose link seems to be broken when you try to get into the details. These are:
sdmx-code, eac-cpf, sdmx-dimension, geos, wf-infoc, iso-thes, lmf, ma-ont, muo, p-plan, pkm, psys, quty, xsd.
And two things to improve the usability of the Web. It will be good to have a dump of the whole .n3 files of each vocabulary separated. Also you should indicate that the timeline of versions of the vocabularies is a slide because I could not notice it at first.

**Comment by pyvandenbussche** [comment]
latest .n3 version link is now displayed for each vocabulary

**Comment by pyvandenbussche** [comment]
Broken Links checked: fixed a bug when prefix with Hyphen. / some of the vocabs have their prefix changed
