### ISSUE TITLE
502 Bad Gateway when creating new version

### ISSUE THREAD

**Issue by unsteady** [pyvandenbussche/lov#29]
I tried to add a new version for doap. The "save" action yielded a 502 error.
Maybe related to #30

**Comment by unsteady** [comment]
Same problem when modifying versions to review, but the modifications are saved

**Comment by pyvandenbussche** [comment]
Not reproduceable

**Comment by pyvandenbussche** [comment]
Be careful!!!!!! import only n3 files for now as version
