### ISSUE TITLE
Creation timeout when creating a vocab

### ISSUE THREAD

**Issue by unsteady** [pyvandenbussche/lov#33]
Certainly linked to adding an agent on the fly
http://lov.okfn.org/dataset/lov/agents/Karsten%20Schmidt 
was created when trying to add "deps"

Agent is created OK
The vocab deps seems to be created, appears on the front page but http://lov.okfn.org/dataset/lov/vocabs/deps is 404

**Comment by unsteady** [comment]
Same issue with dbug creation
http://lov.okfn.org/dataset/lov/vocabs/dbug is 404

**Comment by pyvandenbussche** [comment]
Issue with the addition of an existing agent (agent._id was used instead of agent.id).
