### ISSUE TITLE
Ill formed namespace

### ISSUE THREAD

**Issue by alberto-ieru** [pyvandenbussche/lov#37]
When processing maso vocabulary I am getting a warning and maybe is because a problem in the namespace.
e.g. http://securitytoolbox.appspot.com/MASO#Objectif
Thanks

**Comment by pyvandenbussche** [comment]
Hi,
I need a bit more information to reproduce this issue: what exactly are you processing?
Is it the n3 file stored in LOV, the URI? What type of warning do you have? Can you past here the warning log trace?

Thank you.

**Comment by alberto-ieru** [comment]
I am processing the .n3 file stored in LOV using the Python library rdflib. I am having this trace:

WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Antivirus  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Protocole- Cryptage does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Algorithme- Cryptage does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Virus  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Antivirus  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Virus  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Pers onne does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Objectif  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:http://securitytoolbox.appspot.com/MASO#Antivirus  does not look like a valid URI, trying to serialize this will break.

**Comment by pyvandenbussche** [comment]
The same warnings appear in my log. The problem is in the source vocab RDF file. Will contact the authors and put you in copy. Such warnings are raised here and there ... humans make errors :)

**Comment by pyvandenbussche** [comment]
We already sent multiple emails to the author but he never replied ... We can't do much for that vocab ...
