### ISSUE TITLE
auto-visualize

### ISSUE THREAD

**Issue by marciazeng** [pyvandenbussche/lov#38]
I use WebVOWL  to get a general idea of the classes, properties, and structure of any vocabulary, by appending its IRI to the end of this URL: http://vowl.visualdataweb.org/webvowl/#iri=  E.g., ADMS: http://vowl.visualdataweb.org/webvowl/#iri=http://www.w3.org/ns/adms
Bibo ontology: http://vowl.visualdataweb.org/webvowl/#iri=http://purl.org/ontology/bibo/
Maybe this could be a feature (just a link) to be added to LOV in the future?﻿

**Comment by gatemezing** [comment]
Yes @marciazeng, that could be a nice feature!  Thanks for suggesting.

**Comment by pyvandenbussche** [comment]
This is now done. The link appears for all vocabs. On the right side of each vocab page.
