### ISSUE TITLE
Add a FAQ page to the wiki

### ISSUE THREAD

**Issue by unsteady** [pyvandenbussche/lov#42]
- Is my vocabulary LOV-able?
- Why don't you take SKOS vocabularies?
- Why don't you take OBO vocabularies?
- Does size matters?

**Comment by pyvandenbussche** [comment]
Should that be on the github wiki or in the about page?

**Comment by unsteady** [comment]
I would rather keep the documentation as light as it is now, and add a link to the Wiki from the front page.
