### ISSUE TITLE
Bot reviews and version history to check

### ISSUE THREAD

**Issue by unsteady** [pyvandenbussche/lov#44]
The following is the list of vocabs which have an old BOT review, generally linked to a broken version history with false positive. 
TODO for each of those
- double-check the version history 
- delete the BOT reviews in the vocabulary record
- update the list below when done

 cro
 daq
 date
 dbpedia-owl
 decision
 dogont
 dq
 drm
 dsn
 eac-cpf
 ebucore
 edm
 ext
 fea
 frbrer
 gd
 geofla
 gm
 gndo
 gtfs
 gvp
 h2o
 homeActivity
 homeWeather
 hydra
 identity
 ignf
 inno
 itm
 kdo
 lawd
 ldr
 lexinfo
 lgdo
 li
 limo
 limoo
 lingvo
 lvont
 md
 msm
 mtlo
 nao
 ngeo
 oa
 oad
 obsm
 oc
 of
 ofrd
 oh
 om
 ontosec
 oslc
 osr
 p-plan
 passim
 pav
 person
 plo
 prov
 pwo
 qb
 rdau
 rdfa
 rec54
 reegle
 rr
 ruto
 sam
 saws
 schema
 sdmx
 sio
 smg
 spcm
 spfood
 sql
 ssso
 teach
 test
 theatre
 thors
 tisc
 tm
 topo
 traffic
 umbel
 uri4uri
 vaem
 vag
 vivo
 vrank
 wf-invoc
 whisky
 wikim
 wot

**Comment by pyvandenbussche** [comment]
The version history has to be done systematically on all the vocabs. Bot review deleted automatically.
