### ISSUE TITLE
Suggest should allow submitting a new version

### ISSUE THREAD

**Issue by VladimirAlexiev** [pyvandenbussche/lov#47]
How can I tell LOV that a vocab has a new version? If I try http://lov.okfn.org/dataset/lov/suggest, it says 
"Thank you for suggesting http://vocab.getty.edu/ontology vocabulary.
This vocabulary is already part of the Linked Open Vocabularies ecosystem. You can access the gvp vocabulary page to get more information."
That's true but not helpful :-)

**Comment by gatemezing** [comment]
Hi @VladimirAlexiev, you don't need to tell LOV that information. If you correctly add the properties in the ontology, LOV-Bot is able to tell us (the curators) that we have a new version. HTH.

**Comment by VladimirAlexiev** [comment]
Do you mean that it periodically checks for new versions?
Or when I "suggest", it picks up the new version? In that case, the message cn be improved.

BTW, thanks to this functioanality I found out that GVP as deployed (3.0) is 11 months behind the last update. Version 3.3 will be deployed hopefully today

**Comment by gatemezing** [comment]
LOV Bot checks each day for a new version of an existing URI in LOV. So, if you add relevant metadata to a vocab (modified date, version info), the Bot triggers a message telling there is a new version that a "human" can check.

**Comment by VladimirAlexiev** [comment]
GVP is http://vocab.getty.edu/ontology
