### ISSUE TITLE
Disabled Signup button

### ISSUE THREAD

**Issue by noorbakerally** [pyvandenbussche/lov#55]
I have deployed the lov application from the code from github on my server, I am trying to signup from the app on the url ../edition/lov/signup, but the NEXT button remains disable, any idea﻿, here also it is disable

**Comment by pyvandenbussche** [comment]
The way the backend has been created is for each user to be linked to an existing agent in the database. It's true there is something missing here ... 
I would recommend you to add a user in the mongodb database:
db.agents.insert({ "prefUri" : "http://YOUR_URI", "name" : "YOUR NAME","type" : "person"})
Then as you signup, you will start entering your name and it will bind your user account to that agent ...

**Comment by noorbakerally** [comment]
When i'm adding a vocabulary on ../edition/lov/vocabs/new, it asks for a new tag, but the tag cannot be entered, is there any vocabulary that should be added for a predefined set of tags,
thanks

**Comment by noorbakerally** [comment]
Is there anything we should add more to the database, because i'm having the following issues:
1. No tags showing up when clicking on select tag
2. No Language showing up in the list when adding a title

**Comment by pyvandenbussche** [comment]
I added some files to populate the database (and updated the readme). You should be able to populate all the languages and a list of tags (you can of course update them). 
At the moment the edition does not enable to modify the languages neither the tags. Any help welocmed!

**Comment by gatemezing** [comment]
@noorbakerally  Could we close this issue?

**Comment by noorbakerally** [comment]
Sorry, yeah, I close it, thanks !!
