### ISSUE TITLE
LOV API via https

### ISSUE THREAD

**Issue by LaurensRietveld** [pyvandenbussche/lov#62]
Are there any plans to publish the API via https as well?
This is particularly useful when the API is used by other websites that _do_ run via https. This currently results in a browser warning and failed request.
This is problematic when people use YASGUI via https, as the property and class autocompletion functionality won't work anymore. 

I suggest using letsencrypt (free and automated ssl certs)

**Comment by pyvandenbussche** [comment]
Can you give it a try? It should be fixed now

**Comment by LaurensRietveld** [comment]
wow, that was fast, it works, thanks!

**Comment by pyvandenbussche** [comment]
I used let's encrypt on another server a month ago so was straight forward ;)
