### ISSUE TITLE
LOV suggest following redirections

### ISSUE THREAD

**Issue by gatemezing** [pyvandenbussche/lov#63]
This vocabulary raises an error in the suggestion interface http://ontosoft.org/ontology/software because it makes double redirections (301) due to a server restriction. However it can be loaded into Protégé and can be Curl-able curl -sH "accept:application/rdf+xml" -L.  How to improve the Bot to handle such redirections?

**Comment by pyvandenbussche** [comment]
The Bot uses Jena to access with content negotiation a vocabulary. Not a lot we can do here.

**Comment by gatemezing** [comment]
Thanks! I put it there just in case we have an effort from Jena folks one day ;)

**Comment by dgarijo** [comment]
Relying on Jena to do the negotiaiton might be troublesome also in cases where an ontology uses https and http for content negotiation. For example, any w3id.org vocabulary would not work.
The way I have solved this in the past is to do the content negotiation myself, and then load the vocabulary in Jena

**Comment by gatemezing** [comment]
It would be interesting to ask this question in the Jena list.. I guess they might have an answer to this or maybe they have this issue in their radar

**Comment by gatemezing** [comment]
@dgarijo re w3id.org we have already some of them in LOV.. see for example https://w3id.org/dio

**Comment by dgarijo** [comment]
@gatemezing That onto does a 302 content negotiation. If it's 303, it doesn't work see if the bot gails with: https://w3id.org/games/spec/asteroids

**Comment by gatemezing** [comment]
That's why they are not all in LOV ;)

**Comment by dgarijo** [comment]
Yeah, but the ontologies are well published, and content negotiation is correct. So it's not a problem of the ontology, it's a problem of the tool being used to load the ontology in LOV :(

**Comment by gatemezing** [comment]
Yep.. Tool dependency chain ;) 
I am sure you'll find a workaround to fix this issue to be able "suggest" properly for LOV ;)

**Comment by pyvandenbussche** [comment]
I guess there is a deeper problem.
- There is a content negotiation negotiation with http://ontosoft.org/software. The declared URI of the vocabulary can not be dereferenciated. http://linkeddata.uriburner.com:8000/vapour?uri=http%3A%2F%2Fontosoft.org%2Fsoftware&acceptRdfXml=1&defaultResponse=dontmind&userAgent=http%3A%2F%2Flinkeddata.uriburner.com%3A8000%2Fvapour%23this
- the ontology URI is http://ontosoft.org/software whereas it is published at http://ontosoft.org/ontology/software/ You could avoid a redirection by changing one of these URL.

**Comment by gatemezing** [comment]
@dgarijo  Are you happy with the suggestions? Could we close this issue? TIA
