### ISSUE TITLE
Invalid IRI in N-QUADS dump

### ISSUE THREAD

**Issue by gatemezing** [pyvandenbussche/lov#66]
Issue reported by today @nandana and some months ago by @nogales. 
See URL - http://lov.okfn.org/lov.nq.gz

<http://securitytoolbox.appspot.com/MASO#Protocole- signature>
<http://securitytoolbox.appspot.com/MASO#Objectif >
<http://securitytoolbox.appspot.com/MASO#Antivirus >
<http://securitytoolbox.appspot.com/MASO#Algorithme- >
<http://securitytoolbox.appspot.com/MASO#Virus >
<http://securitytoolbox.appspot.com/MASO#Pers >

**Comment by pyvandenbussche** [comment]
lov dumps and latest version of each vocabularies are now free of syntax error.

**Comment by gatemezing** [comment]
Thanks @pyvandenbussche ! 
I've downloaded today the new dump, but still get some errors using rapper. Not sure if it's a different issue here... Also when trying to import with [Dydra](https://dydra.com/ghislain/lovdydra), I have the error "term is shorter than minimum length on line 720873, column 2. 
See below:
rapper: Parsing URI file:///Users/gatemezing/Downloads/lov_2.nq with parser nquads
rapper: Serializing with serializer turtle
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720873 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720874 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720875 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720876 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720877 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720878 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720879 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720880 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720881 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720882 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720883 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720884 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720885 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720886 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720887 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720888 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720889 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720890 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:720891 column 2 - URI '' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:724682 column 105 - URI 'soroosh@cs.toronto.edu' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:724974 column 119 - URI 'www.beniculturali.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:724988 column 117 - URI 'www.beniculturali.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:729537 column 112 - URI 'dataplatform@kadaster.nl' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:736551 column 18 - URI 'www.maas.ccr.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:736552 column 18 - URI 'www.maas.ccr.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:736835 column 100 - URI 'stefan.schulz@medunigraz.at' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:756726 column 112 - URI 'dataplatform@kadaster.nl' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:761215 column 24 - URI 'jesus.bermudez@ehu.eus' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:761216 column 24 - URI 'jesus.bermudez@ehu.eus' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:770167 column 93 - URI 'www.maas.ccr.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:772430 column 91 - URI 'diarmuidr3d@gmail.com' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:772738 column 29 - URI 'stefan.schulz@medunigraz.at' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:772739 column 29 - URI 'stefan.schulz@medunigraz.at' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:776841 column 26 - URI 'iker.esnaola@tekniker.es' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:776842 column 26 - URI 'iker.esnaola@tekniker.es' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:777568 column 26 - URI 'dataplatform@kadaster.nl' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:777569 column 26 - URI 'dataplatform@kadaster.nl' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:780271 column 23 - URI 'www.beniculturali.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:780272 column 23 - URI 'www.beniculturali.it/' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:781752 column 116 - URI 'dataplatform@kadaster.nl' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:781935 column 24 - URI 'soroosh@cs.toronto.edu' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:781936 column 24 - URI 'soroosh@cs.toronto.edu' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:784762 column 84 - URI 'jesus.bermudez@ehu.eus' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:784764 column 86 - URI 'iker.esnaola@tekniker.es' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:785224 column 23 - URI 'diarmuidr3d@gmail.com' is not absolute.
rapper: Error - URI file:///Users/gatemezing/Downloads/lov_2.nq:785225 column 23 - URI 'diarmuidr3d@gmail.com' is not absolute.
rapper: Parsing returned 789733 triples
