### ISSUE TITLE
How does the vocabulary recommender work? 

### ISSUE THREAD

**Issue by rezacsedu** [pyvandenbussche/lov#70]
Hi,

How does the vocabulary recommender work and provide the ranking (http://lov.okfn.org/dataset/lov/terms/)? 
A pointer would be very helpful.

**Comment by pyvandenbussche** [comment]
Hi,

You can find details on the LOV search engine and the ranking method used in section 3.3.1 of this article: 
http://www.semantic-web-journal.net/system/files/swj1178.pdf
Best,
